app:
    resource: "@AppBundle/Controller/"
    type:     annotation

candidatures:
    resource: "@CandidaturesBundle/Controller/"
    type:     annotation
    prefix:   /

oc_user_chomeur:
    resource: "@OCUserBundle/Controller/ChomeurController.php"
    type:     annotation

oc_user_entreprise:
    resource: "@OCUserBundle/Controller/EntrepriseController.php"
    type:     annotation

qcm:
    resource: "@QcmBundle/Controller/"
    type:     annotation

# Configuration des pages FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
